addSbtPlugin("com.typesafe.sbt"   %  "sbt-native-packager"   % "1.3.6")
addSbtPlugin("com.typesafe.sbt"   %  "sbt-site"              % "1.3.2")
addSbtPlugin("net.virtual-void"   %  "sbt-dependency-graph"  % "0.9.1")
addSbtPlugin("org.scalariform"    %  "sbt-scalariform"       % "1.8.2")
addSbtPlugin("org.scoverage"      %  "sbt-scoverage"         % "1.5.1")
addSbtPlugin("org.scalastyle"     %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.tpolecat"       %  "tut-plugin"            % "0.6.7")
